name: Fly Deploy

on:
  push:
    branches:
      - master
    paths:
      - "weekly_deaths/cmd/**"
      - "weekly_deaths/internal/**"
      - "weekly_deaths/fly.toml"
      - .github/workflows/fly.yml

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go test ./...
        working-directory: ./weekly_deaths

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --build-arg COMMIT=$(git rev-parse HEAD) --remote-only
        working-directory: ./weekly_deaths
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
